elasticsearch:
  host: localhost
  port: 9200

logging:
  level:
    org.springframework: INFO
    org.es: DEBUG

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/avmDB?characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql